project_id = "plwwqnfixocdbhsswiyr"

[functions.generate-recipe]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false