project_id = "plwwqnfixocdbhsswiyr"

[functions.generate-recipe]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.generate-meal-planner-day]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.reset-credit-bonus]
verify_jwt = false

[functions.generate-recipe-image-gemini]
verify_jwt = false

[functions.admin-resolve-user-id]
verify_jwt = false
